name: honeywouldyou
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # redux
  redux: 2.0.4
  rxdart: 0.15.0
  flutter_redux: 0.3.4
  redux_logging: 0.1.4
  redux_epics: 0.6.1

  # navigation
  fluro: 1.2.1

  # immutable
  built_value: 4.4.0

  # Firebase
  firebase_auth: 0.3.1
  cloud_firestore: 0.1.1
  google_sign_in: 1.0.1


  # utils
  uuid: 0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: 0.0.5
  flutter_driver:
    sdk: flutter
  
  build_runner: 0.5.0
  built_value_generator: 4.4.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/mock/lists.json
   - assets/images/google_signin_buttons/logo_googleg.png
  #  - images/a_dot_ham.jpeg

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 200

  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Thin.ttf
        weight: 100

  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 700
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-ExtraLight.ttf
        weight: 200

  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSans-Regular.ttf
        weight: 400

  - family: VarelaRound
    fonts:
      - asset: assets/fonts/VarelaRound-Regular.ttf
        weight: 400


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
